spring:
  redis:
    database: 0
    host: 192.168.10.11
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 1000

server:
  port: 80

eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

